# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c6ec42cb13a6836e5cfd5522b31a3a9df95f0751894f10271375e54c69804dee45817b9675ae666f96f5420f2e5368cb7feca59f5dec118fefe5fbad749a490

test:
  secret_key_base: 9bb92b168e4edc3f853fde02907ff9098336da86062becf15e22a36f6557ed1d8c2cf4e32af91fb4e1ba0ae84f777301ffe994e5c636c45e6488d4b69c755d33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
